program Halifax;

uses
  Vcl.Forms,
  View_Style in 'View\Styles\View_Style.pas',
  Model.Conexao_FDAC in 'Model\Conexao\Model.Conexao_FDAC.pas',
  Model.Conexao_IB in 'Model\Conexao\Model.Conexao_IB.pas',
  Model.Conexao_Interface in 'Model\Conexao\Model.Conexao_Interface.pas',
  Model.DAO.Cad_Consultas_FDAC in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Consultas_FDAC.pas',
  Model.DAO.Cad_Usuario_IB in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Usuario_IB.pas',
  Model.DAO.Cad_Usuario_Interface in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Usuario_Interface.pas',
  Model.ORM_Loc_M1_Cad_Permissoes in 'Model\ORM_MapeamentoObjetoRelacional\Cadastros\Model.ORM_Loc_M1_Cad_Permissoes.pas',
  Model.ORM_Loc_M1_Cad_Usuario in 'Model\ORM_MapeamentoObjetoRelacional\Cadastros\Model.ORM_Loc_M1_Cad_Usuario.pas',
  MODEL.ORM_Loc_M1_LocacaoCabecalho in 'Model\ORM_MapeamentoObjetoRelacional\Locacoes\MODEL.ORM_Loc_M1_LocacaoCabecalho.pas',
  MODEL.ORM_Loc_M1_Produtos in 'Model\ORM_MapeamentoObjetoRelacional\Produtos\MODEL.ORM_Loc_M1_Produtos.pas',
  MODEL.ORM_Loc_M1_ProdutosEstoque in 'Model\ORM_MapeamentoObjetoRelacional\Produtos\MODEL.ORM_Loc_M1_ProdutosEstoque.pas',
  MODEL.ORM_Loc_M1_ProdutosManutencao in 'Model\ORM_MapeamentoObjetoRelacional\Produtos\MODEL.ORM_Loc_M1_ProdutosManutencao.pas',
  MODEL.ORM_Loc_M1_ProdutosPreco in 'Model\ORM_MapeamentoObjetoRelacional\Produtos\MODEL.ORM_Loc_M1_ProdutosPreco.pas',
  uLocacacaoDeMateriais_Principal in 'uLocacacaoDeMateriais_Principal.pas' {_Frm_Principal},
  VIEW.Cadastros.Consultas in 'View\Cadastros\VIEW.Cadastros.Consultas.pas' {View_CadastrosConsulta},
  Parametros.CaminhoBancoDeDados in 'Parametros\Parametros.CaminhoBancoDeDados.pas',
  Halifax.Controller.Cad_UsuariosIB in 'Controller\Cadastros\Halifax.Controller.Cad_UsuariosIB.pas',
  Halifax.Controller.Cad_UsuariosIB_Interface in 'Controller\Cadastros\Halifax.Controller.Cad_UsuariosIB_Interface.pas',
  Halifax.Controller.Cad_UsuariosFD_Interface in 'Controller\Cadastros\Halifax.Controller.Cad_UsuariosFD_Interface.pas',
  Halifax.Controller.Cad_UsuarioFD in 'Controller\Cadastros\Halifax.Controller.Cad_UsuarioFD.pas',
  Model.DAO.Cad_Usuario_FDAC in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Usuario_FDAC.pas',
  Halifax.Controller.Cad_ConsultasFD_Interface in 'Controller\Cadastros\Halifax.Controller.Cad_ConsultasFD_Interface.pas',
  Halifax.Controller.Cad_ConsultasFD in 'Controller\Cadastros\Halifax.Controller.Cad_ConsultasFD.pas',
  Parametros.ParametrosPermissoes in 'Parametros\Parametros.ParametrosPermissoes.pas',
  Parametros.ParametrosGlobais in 'Parametros\Parametros.ParametrosGlobais.pas',
  Model.DAO.Cad_Consultas_IB in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Consultas_IB.pas',
  View.Padrao_Lixeira in 'View\Padrao\View.Padrao_Lixeira.pas' {Form_ConfirmaLixeira},
  VIEW.Cadastros.PermissoesCadastros in 'View\Cadastros\VIEW.Cadastros.PermissoesCadastros.pas' {View_PermissoesCadastros},
  VIEW.Cadastros.UsuariosCadastros in 'View\Cadastros\VIEW.Cadastros.UsuariosCadastros.pas' {View_UsuariosCadastros},
  VIEW.Cadastros.UsuariosConsultas in 'View\Cadastros\VIEW.Cadastros.UsuariosConsultas.pas' {View_UsuariosConsultas},
  Model.DAO.Cad_Permissoes_FDAC in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Permissoes_FDAC.pas',
  Model.DAO.Cad_Permissoes_Interface in 'Model\DAO_DirectAcessObject\Cadastros\Model.DAO.Cad_Permissoes_Interface.pas',
  Halifax.Controller.Cad_PermissoesFD_Interface in 'Controller\Cadastros\Halifax.Controller.Cad_PermissoesFD_Interface.pas',
  Halifax.Controller.Cad_PermissoesFD in 'Controller\Cadastros\Halifax.Controller.Cad_PermissoesFD.pas',
  VIEW.PadraoBasico01 in 'View\Padrao\VIEW.PadraoBasico01.pas' {_F_CadastroPadrao},
  VIEW.PadraoBasico01_Interface in 'View\Padrao\VIEW.PadraoBasico01_Interface.pas',
  Model.DAO.Produtos_FD in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.Produtos_FD.pas',
  Model.DAO.Produtos_FD_Interface in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.Produtos_FD_Interface.pas',
  Model.DAO.ProdutosEstoque_FD_Interface in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosEstoque_FD_Interface.pas',
  Model.DAO.ProdutosManutencao_FD in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosManutencao_FD.pas',
  Model.DAO.ProdutosPreco_FD in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosPreco_FD.pas',
  Model.DAO.ProdutosManutencao_FD_Interface in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosManutencao_FD_Interface.pas',
  Hallifax.Controller.Produtos.ProdutosPreco in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosPreco.pas',
  Hallifax.Controller.Produtos.Produtos_Interface in 'Controller\Produtos\Hallifax.Controller.Produtos.Produtos_Interface.pas',
  Hallifax.Controller.Produtos.ProdutosManutencao_Interface in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosManutencao_Interface.pas',
  Hallifax.Controller.Produtos.ProdutosPreco_Interface in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosPreco_Interface.pas',
  Hallifax.Controller.Produtos.Produtos in 'Controller\Produtos\Hallifax.Controller.Produtos.Produtos.pas',
  Hallifax.Controller.Produtos.ProdutosManutencao in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosManutencao.pas',
  VIEW.Produtos.ProdutosConsultas in 'View\Produtos\VIEW.Produtos.ProdutosConsultas.pas' {View.Produtos.ProdutosConsultas},
  VIEW.Login in 'VIEW.Login.pas' {VIEW_Login},
  VIEW.Padrao.Parametros1 in 'View\Padrao\VIEW.Padrao.Parametros1.pas' {View_Parametros1},
  VIEW.Produtos.Produtos in 'View\Produtos\VIEW.Produtos.Produtos.pas' {View_ProdutosDados},
  VIEW.Produtos.Preco in 'View\Produtos\VIEW.Produtos.Preco.pas' {View_ProdutosPreco},
  VIEW.Produtos.Manutencao in 'View\Produtos\VIEW.Produtos.Manutencao.pas' {View_ProdutosManutencao},
  Model.DAO.ProdutosPreco_FD_Interface in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosPreco_FD_Interface.pas',
  Model.DAO.ProdutosEstoque_FD in 'Model\DAO_DirectAcessObject\Produtos\Model.DAO.ProdutosEstoque_FD.pas',
  Hallifax.Controller.Produtos.ProdutosEstoque_Interface in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosEstoque_Interface.pas',
  Hallifax.Controller.Produtos.ProdutosEstoque in 'Controller\Produtos\Hallifax.Controller.Produtos.ProdutosEstoque.pas',
  VIEW.Produtos.Estoque in 'View\Produtos\VIEW.Produtos.Estoque.pas' {View_ProdutosEstoque},
  MODEL.ORM_Loc_M1_LocacaoPgtoItens in 'Model\ORM_MapeamentoObjetoRelacional\Locacoes\MODEL.ORM_Loc_M1_LocacaoPgtoItens.pas',
  Model.DAO.LocacoesCabecalho_FD in 'Model\DAO_DirectAcessObject\Locacoes\Model.DAO.LocacoesCabecalho_FD.pas',
  MODEL.ORM_Loc_M1_LocacaoItens in 'Model\ORM_MapeamentoObjetoRelacional\Locacoes\MODEL.ORM_Loc_M1_LocacaoItens.pas',
  Model.DAO.LocacoesCabecalhoItens_FD_Interface in 'Model\DAO_DirectAcessObject\Locacoes\Model.DAO.LocacoesCabecalhoItens_FD_Interface.pas',
  Model.DAO.LocacoesItens_FD in 'Model\DAO_DirectAcessObject\Locacoes\Model.DAO.LocacoesItens_FD.pas',
  MODEL.ORM_ContasReceber in 'Model\ORM_MapeamentoObjetoRelacional\Financeiro\MODEL.ORM_ContasReceber.pas',
  Model.DAO.Financeiro.ContasReceber_FD_Interface in 'Model\DAO_DirectAcessObject\Financeiro\Model.DAO.Financeiro.ContasReceber_FD_Interface.pas',
  Model.DAO.Financeiro.ContasReceber_FD in 'Model\DAO_DirectAcessObject\Financeiro\Model.DAO.Financeiro.ContasReceber_FD.pas',
  Hallifax.Controller.Financeiro.ContasReceber_Interface in 'Controller\Financeiro\Hallifax.Controller.Financeiro.ContasReceber_Interface.pas',
  Hallifax.Controller.Financeiro.ContasReceber in 'Controller\Financeiro\Hallifax.Controller.Financeiro.ContasReceber.pas',
  Hallifax.Controller.Locacoes.LocacoesCabecalho_FD in 'Controller\Locacoes\Hallifax.Controller.Locacoes.LocacoesCabecalho_FD.pas',
  Hallifax.Controller.Locacoes.LocacoesCabecalho_FD_Interface in 'Controller\Locacoes\Hallifax.Controller.Locacoes.LocacoesCabecalho_FD_Interface.pas',
  Hallifax.Controller.Locacoes.LocacoesItens_FD_Interface in 'Controller\Locacoes\Hallifax.Controller.Locacoes.LocacoesItens_FD_Interface.pas',
  Hallifax.Controller.Locacoes.LocacoesItens_FD in 'Controller\Locacoes\Hallifax.Controller.Locacoes.LocacoesItens_FD.pas',
  VIEW.Locacoes.LocacoesConsultas in 'View\Locacoes\VIEW.Locacoes.LocacoesConsultas.pas' {View_LocacoesConsulta},
  VIEW.Locacoes.Locacoes in 'View\Locacoes\VIEW.Locacoes.Locacoes.pas' {VIEW_LocacoesMovimentacao};

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TVIEW_Login, VIEW_Login);
  Application.CreateForm(TView_Parametros1, View_Parametros1);
  Application.Run;
end.
